services:
  db:
    image: mysql
    container_name: despesas_pessoais
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - despesas_data:/var/lib/mysql

volumes:
  despesas_data: